# 生产环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.79.10:3306/lee_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: lee
    password: li15854198694
  # redis配置
  redis:
    host: 192.168.79.10
    port: 6379
    password: li15854198694
  # rabbitmq配置
  rabbitmq:
    host: 192.168.79.10
    port: 5672
    username: root
    password: 123
  # es配置
  elasticsearch:
    rest:
      uris: 192.168.79.10:9200
