server:
  port: 8080
  servlet:
    session:
      timeout: 21600
      
  # 默认是8KB
  max-http-header-size: 16384
  
spring:
  profiles:
    active: prod

  # 邮箱配置
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory
  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size:  50MB

# 网站域名，用于邮件通知
website:
  url: https://www.lovesky.top

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

# 上传模式 可选 oss或local  （/一定不能去！！！）
upload:
  mode: oss
  local:
    # nginx映射本地文件路径
    url: https://upload.lovesky.top/
    # 本地文件存储路径
    path: /usr/local/upload/
  oss:
    url: https://*****.aliyuncs.com/
    endpoint: https://*****.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName:

weibo:
  app-id:
  app-secret:
  grant-type: authorization_code
  redirect-url: https://www.lovesky.top
  access-token-url: https://api.weibo.com/oauth2/access_token
  user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}
